project_id = "lnxbvkcggoyfmpfthhhk"

[functions.generate-bpmn]
verify_jwt = true
max_body_size = "2mb"
request_timeout = 150

[functions.generate-bpmn-combined]
verify_jwt = true
request_timeout = 300

[functions.speech-to-text]
verify_jwt = true

[functions.vision-to-bpmn]
verify_jwt = true

[functions.chatbot]
verify_jwt = true

[functions.refine-bpmn]
verify_jwt = true

[functions.analyze-document-to-bpmn]
verify_jwt = true

[functions.screen-recording-to-bpmn]
verify_jwt = true

[functions.refine-dmn]
verify_jwt = true

[functions.generate-dmn]
verify_jwt = true

[functions.bottleneck-metrics]
verify_jwt = true

[functions.track-visitor]
verify_jwt = false

[functions.process-bpmn-job]
verify_jwt = true
