project_id = "lnxbvkcggoyfmpfthhhk"

[functions.generate-bpmn]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.vision-to-bpmn]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.refine-bpmn]
verify_jwt = false

[functions.analyze-document-to-bpmn]
verify_jwt = false

[functions.screen-recording-to-bpmn]
verify_jwt = false

[functions.refine-dmn]
verify_jwt = false
