version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prossmind-lambda-stack"
s3_prefix = "prossmind-lambda-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SupabaseUrl=\"https://lnxbvkcggoyfmpfthhhk.supabase.co\" SupabaseServiceRoleKey=\"\" AwsRegion=\"us-east-1\""
image_repositories = []
